spring:
  application:
    name: notification-service
  mail:
    port: ${MAIL_PORT}
    host: ${MAIL_HOST}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    from: ${MAIL_FROM}
  main:
    banner-mode: off
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    properties:
      security.protocol: ${KAFKA_SECURITY_PROTOCOL:PLAINTEXT}
      sasl.mechanism: ${KAFKA_SASL_MECHANISM:PLAIN}
      sasl.jaas.config: ${KAFKA_SASL_JAAS_CONFIG:}
logging:
  level:
    root: warn
app:
  client-url: ${CLIENT_URL}



server:
  port: ${SERVER_PORT}