spring:
  application:
    name: item-service
  main:
    banner-mode: off
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    properties:
      security.protocol: ${KAFKA_SECURITY_PROTOCOL:PLAINTEXT}
      sasl.mechanism: ${KAFKA_SASL_MECHANISM:PLAIN}
      sasl.jaas.config: ${KAFKA_SASL_JAAS_CONFIG:}
  datasource:
    url: ${DATASOURCE_URL}
    password: ${DB_PASSWORD}
    username: ${DB_USER}
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${JWK_SET_URI}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
server:
  port: ${SERVER_PORT}
logging:
  level:
    root: warn
